version: "3.8"
services:
  backend:
    build: /home/user/gold-tracker/backend
    volumes:
      - /home/user/gold-tracker/data:/app/data
    restart: always

  frontend:
    build: /home/user/gold-tracker/frontend
    ports:
      - "8180:80"
    volumes:
      - /home/user/gold-tracker/data:/usr/share/nginx/html
    restart: always
