version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gold_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8180:80"
    restart: always

volumes:
  pgdata:
