version: "3.8"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend/gold_prices.db:/app/gold_prices.db
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8180:80"
    restart: always
