version: "3.8"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gold_tracker
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/gold_tracker
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8180:80"
    restart: always

volumes:
  pgdata:
